name: linter

on:
  push:
    branches: [master, *]

jobs:
  linter-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        id: pip-cache
        with:
          path: |
            ~/. cahe/pip
          key: pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install requirements
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - name: Run flake8
        run: |
          echo 'Run flake8'
          flake8 .
